In [1]:
import pandas as pd

df = pd.read_feather("/Users/moritzbeckmail.de/Documents/Phd/Research/NixtlaForecast/data/preprocessed_data.feather")

df

,skuID,date,demand,companyID,storeID,productID,missing_value,not_for_sale,mean_demand,std_demand,...,percentile_70_demand,percentile_90_demand,inter_quartile_range,feature_0000,feature_0001,feature_0002,feature_0003,feature_0004,feature_0005,feature_0006
0,2245,2016-01-02,0.635300,11.0,1125.0,11.0,0.0,0.0,0.015998,0.996677,...,-0.174943,1.863074,0.437969,0.0,1.0,2.058601,-0.981193,-1.318386,-0.464409,0.0
1,2245,2016-01-03,2.708354,11.0,1125.0,11.0,0.0,0.0,0.015998,0.996677,...,-0.174943,1.863074,0.437969,0.0,1.0,0.435688,-0.914979,-1.101797,-0.449397,0.0
2,2245,2016-01-04,-0.255237,11.0,1125.0,11.0,0.0,0.0,0.015998,0.996677,...,-0.174943,1.863074,0.437969,0.0,1.0,1.226338,-0.835523,-0.863549,-0.629544,0.0
3,2245,2016-01-05,-0.094648,11.0,1125.0,11.0,0.0,0.0,0.015998,0.996677,...,-0.174943,1.863074,0.437969,0.0,1.0,0.310849,-0.848766,-0.993503,-0.689593,0.0
4,2245,2016-01-06,1.197361,11.0,1125.0,11.0,0.0,0.0,0.015998,0.996677,...,-0.174943,1.863074,0.437969,1.0,1.0,-0.396575,-0.716338,-0.852720,-0.449397,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121258,2349,2019-04-26,-1.369510,11.0,1159.0,13.0,0.0,0.0,0.072185,0.871734,...,0.415204,1.064191,1.081645,0.0,1.0,0.564565,-0.084720,-0.409216,0.125591,0.0
121259,2349,2019-04-27,-0.341947,11.0,1159.0,13.0,0.0,0.0,0.072185,0.871734,...,0.415204,1.064191,1.081645,0.0,1.0,0.818630,-0.111690,-0.096463,0.095122,0.0
121260,2349,2019-04-28,0.793780,11.0,1159.0,13.0,0.0,0.0,0.072185,0.871734,...,0.415204,1.064191,1.081645,0.0,0.0,-0.261148,-0.286992,-0.163481,-0.453324,0.0
121261,2349,2019-04-29,-0.017454,11.0,1159.0,13.0,0.0,0.0,0.072185,0.871734,...,0.415204,1.064191,1.081645,0.0,0.0,1.453794,-0.286992,-0.174651,-0.620905,0.0
121262,2349,2019-04-30,0.036628,11.0,1159.0,13.0,0.0,0.0,0.072185,0.871734,...,0.415204,1.064191,1.081645,0.0,0.0,-0.472869,0.225429,0.372668,-0.026755,0.0

cross_validation:
  cv_windows: 13
  step_size: 14
  refit: false

In [2]:
n_windows = 6
step_size = 1  # days
offset = pd.Timedelta(days=n_windows * step_size)

df_fit = df[df["date"] < df["date"].max() - offset]

In [3]:
import pandas as pd

df_fit = pd.read_csv("df_fit.csv", parse_dates=["date"])
df_fit

        skuID       date    demand  companyID  storeID  productID
0        2245 2016-01-02  0.635300       11.0   1125.0       11.0
1        2245 2016-01-03  2.708354       11.0   1125.0       11.0
2        2245 2016-01-04 -0.255237       11.0   1125.0       11.0
3        2245 2016-01-05 -0.094648       11.0   1125.0       11.0
4        2245 2016-01-06  1.197361       11.0   1125.0       11.0
...       ...        ...       ...        ...      ...        ...
120646   2349 2019-04-20 -1.639921       11.0   1159.0       13.0
120647   2349 2019-04-21 -1.639921       11.0   1159.0       13.0
120648   2349 2019-04-22 -0.287865       11.0   1159.0       13.0
120649   2349 2019-04-23 -1.369510       11.0   1159.0       13.0
120650   2349 2019-04-24  0.144793       11.0   1159.0       13.0

[120651 rows x 6 columns]

In [4]:
import pickle

# Load dict_fit

with open("dict_fit.pkl", "rb") as f:
    dict_fit = pickle.load(f)

dict_fit

{'df':         skuID       date    demand  companyID  storeID  productID
 0        2245 2016-01-02  0.635300       11.0   1125.0       11.0
 1        2245 2016-01-03  2.708354       11.0   1125.0       11.0
 2        2245 2016-01-04 -0.255237       11.0   1125.0       11.0
 3        2245 2016-01-05 -0.094648       11.0   1125.0       11.0
 4        2245 2016-01-06  1.197361       11.0   1125.0       11.0
 ...       ...        ...       ...        ...      ...        ...
 121252   2349 2019-04-20 -1.639921       11.0   1159.0       13.0
 121253   2349 2019-04-21 -1.639921       11.0   1159.0       13.0
 121254   2349 2019-04-22 -0.287865       11.0   1159.0       13.0
 121255   2349 2019-04-23 -1.369510       11.0   1159.0       13.0
 121256   2349 2019-04-24  0.144793       11.0   1159.0       13.0

 [120651 rows x 6 columns],
 'h': 14,
 'n_windows': 6,
 'step_size': 1,
 'num_samples': 10,
 'refit': False,
 'id_col': 'skuID',
 'target_col': 'demand',
 'time_col': 'date'}

In [ ]:
from mlforecast.auto import AutoMLForecast, AutoLightGBM
model = AutoLightGBM()

auto_ml_frcast = AutoMLForecast(models=[model],
                                init_config=lambda x: {"lags": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
                                                       "date_features": ["dayofweek", "month"],
                                                       },
                                 fit_config=lambda x: {"static_features": ["storeID", "productID", "companyID"],},
                            num_threads=1,
                                freq="D")

auto_ml_frcast.fit(**dict_fit)

/Users/moritzbeckmail.de/miniconda3/envs/nixtla_forecast/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2025-05-30 15:17:53,226] A new study created in memory with name: no-name-d2f98293-db97-4335-a03a-9f64eb736e0f
[I 2025-05-30 15:17:55,619] Trial 0 finished with value: 0.5069405368048886 and parameters: {'n_estimators': 169, 'lambda_l1': 0.027334069690310565, 'lambda_l2': 0.0026599310838681858, 'num_leaves': 112, 'feature_fraction': 0.7118273996694524, 'bagging_fraction': 0.8229470565333281, 'objective': 'l2'}. Best is trial 0 with value: 0.5069405368048886.
[I 2025-05-30 15:18:02,427] Trial 1 finished with value: 0.5115006862834637 and parameters: {'n_estimators': 867, 'lambda_l1': 2.8247087122296067e-05, 'lambda_l2': 0.13351354975517513, 'num_leaves': 99, 'feature_fraction': 0.7840222805469661, 'bagging_fraction': 0.9627983191463305, 'objective': 'l2'}. Best is trial 0 with value: 0.5069405368048886.
[I 2025-05-30 15:18:04,525] Trial 2 finished with value: 0.6317993199862437 and parameters: {'n_estimators': 21, 'lambda_l1': 0.31158648353398066, 'lambda_l2': 0.10078844818976519, 'num_leaves': 1465, 'feature_fraction': 0.989309171116382, 'bagging_fraction': 0.8995792821083618, 'objective': 'l2'}. Best is trial 0 with value: 0.5069405368048886.
[I 2025-05-30 15:18:09,727] Trial 3 finished with value: 0.565949522935774 and parameters: {'n_estimators': 31, 'lambda_l1': 0.005744988873954126, 'lambda_l2': 1.9506510537765813e-07, 'num_leaves': 2644, 'feature_fraction': 0.7609241608750359, 'bagging_fraction': 0.7073309699952618, 'objective': 'l2'}. Best is trial 0 with value: 0.5069405368048886.
[I 2025-05-30 15:18:12,086] Trial 4 finished with value: 0.5009862110777284 and parameters: {'n_estimators': 118, 'lambda_l1': 0.001305886823451577, 'lambda_l2': 1.4760742495197955e-08, 'num_leaves': 199, 'feature_fraction': 0.8060478613612108, 'bagging_fraction': 0.8084669984373785, 'objective': 'l1'}. Best is trial 4 with value: 0.5009862110777284.
[I 2025-05-30 15:18:12,364] Trial 5 pruned.
[I 2025-05-30 15:18:13,144] Trial 6 finished with value: 0.5035135137911583 and parameters: {'n_estimators': 68, 'lambda_l1': 1.8767090076326167e-05, 'lambda_l2': 0.0013544748136111338, 'num_leaves': 48, 'feature_fraction': 0.9941869190296131, 'bagging_fraction': 0.551022405374014, 'objective': 'l1'}. Best is trial 4 with value: 0.5009862110777284.
[I 2025-05-30 15:18:14,158] Trial 7 finished with value: 0.5004559543805441 and parameters: {'n_estimators': 255, 'lambda_l1': 1.9038135910385762e-06, 'lambda_l2': 0.00015732471573476155, 'num_leaves': 10, 'feature_fraction': 0.5794847918227599, 'bagging_fraction': 0.5551875705821525, 'objective': 'l1'}. Best is trial 7 with value: 0.5004559543805441.
[I 2025-05-30 15:18:14,362] Trial 8 pruned.
[I 2025-05-30 15:18:16,065] Trial 9 pruned.

AutoMLForecast(models={'AutoLightGBM': AutoModel(model=LGBMRegressor)})

In [6]:
df = auto_ml_frcast.models_['AutoLightGBM'].cross_validation(df, n_windows=4, h=14, id_col="skuID", time_col="date", target_col="demand", static_features=["storeID", "productID", "companyID"])

In [7]:
df

      skuID       date     cutoff    demand  AutoLightGBM
0      2245 2019-03-06 2019-03-05 -0.664008     -0.598765
1      2245 2019-03-07 2019-03-05 -0.693206     -0.559035
2      2245 2019-03-08 2019-03-05 -0.671308     -0.347436
3      2245 2019-03-09 2019-03-05 -0.518018     -0.001068
4      2245 2019-03-10 2019-03-05  1.730223      2.022602
...     ...        ...        ...       ...           ...
5707   2349 2019-04-26 2019-04-16 -1.369510     -0.305408
5708   2349 2019-04-27 2019-04-16 -0.341947     -0.086036
5709   2349 2019-04-28 2019-04-16  0.793780      0.069402
5710   2349 2019-04-29 2019-04-16 -0.017454     -0.502437
5711   2349 2019-04-30 2019-04-16  0.036628     -0.562951

[5712 rows x 5 columns]